a=int(input("enter a number:"))
b=int(input("enter another number:"))
print("addition: ",a+b)
print("subtraction: ",a-b)
print("multiplication: ",a*b)
print("division: ",a/b)
print("modulo: ",a%b)
print("exponential: ",a**b)
